version: 0.0
os: linux
files:
  - source: .
    destination: /home/ubuntu/Jerry/TestServer/
hooks:
  ApplicationStop:
   - location: scripts/app-start.sh
     timeout: 300
     runas: root
  ApplicationStart:
   - location: scripts/app-start.sh
     timeout: 300
     runas: root