name: CI/CD Pipeline
on:
  push:
    branches: [ master ]

jobs:
  continous-integration:
    runs-on: ubuntu-latest
    
    steps:
        - uses: actions/checkout@v1.0
          name: Check out code

        - uses: mr-smithers-excellent/docker-build-push@v3
          name: Build Docker image
          with:
            dockerfile: Dockerfile
  continuous-deployment:
    runs-on: ubuntu-latest

    steps:
     # Step 1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
     # Step 2
      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          aws deploy create-deployment \
            --application-name Nodejs-autopump \
            --deployment-group-name NodejsAutopump-scaled \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --file-exists-behavior OVERWRITE \
            --auto-rollback-configuration enabled=true,events=DEPLOYMENT_FAILURE \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
